version: '3.9'
services:
  db:
    image: postgres:17.6-alpine
    environment:
      POSTGRES_USER: xcg
      POSTGRES_PASSWORD: xcg
      POSTGRES_DB: xcg
    ports:
      - '5432:5432'
    volumes:
      - ./.data/pg:/var/lib/postgresql/data
